### PR TITLE
reinstall postgres client to update libpq lib

### PR DESCRIPTION
**Pull request by SchramlTim**
**What i did:**
Install amazon-linux-extras
Install through amazon-linux-extras postgres version 10

Only for php versions >= 8
Tested in php version 8.2

### CODE REVIEW

**Comment by Neustradamus** [comment]
@SchramlTim: Thanks for your work!

**Comment by f3l1x** [comment]
Thank you.

**Comment by SchramlTim** [comment]
@f3l1x do you have a schedule when you release the new npm packages?

**Comment by f3l1x** [comment]
Hi @SchramlTim.

New versions are bumped.

vercel-php@0.6.0 - PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.3 - PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.1 - PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.3 - PHP 7.4.x (https://example-php-7-4.vercel.app/)

**Pull request merged**
